# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionitem',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
