# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0002_sectionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
